export const DATA = [
  {
    id: 1,
    orderNumber: 'ORD-001',
    customerName: 'Ali Ahmedov',
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-01',
    pharmacyName: 'Apteka A',
    products: [
      { productName: 'Paracetamol', quantity: 2, price: 3, dosageForm: 'Tablet', strength: '500 mg' },
      { productName: 'Aspirin', quantity: 1, price: 2, dosageForm: 'Tablet', strength: '100 mg' },
    ],
  },
  {
    id: 2,
    orderNumber: 'ORD-002',
    customerName: 'Malika Karimova',
    status: "Jo'natildi",
    orderDate: '2024-08-03',
    pharmacyName: 'Apteka B',
    products: [{ productName: 'Ibuprofen', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '400 mg' }],
  },
  {
    id: 3,
    orderNumber: 'ORD-003',
    customerName: 'Bekzod Rahimov',
    status: 'Yetkazib berildi',
    orderDate: '2024-08-05',
    pharmacyName: 'Apteka C',
    products: [
      { productName: 'Amoxicillin', quantity: 3, price: 5, dosageForm: 'Capsule', strength: '250 mg' },
      { productName: 'Omeprazole', quantity: 1, price: 8, dosageForm: 'Capsule', strength: '20 mg' },
    ],
  },
  {
    id: 4,
    orderNumber: 'ORD-004',
    customerName: 'Dilnoza Tursunova',
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-07',
    pharmacyName: 'Apteka D',
    products: [
      { productName: 'Ciprofloxacin', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '500 mg' },
      { productName: 'Metformin', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '500 mg' },
      { productName: 'Lisinopril', quantity: 2, price: 10, dosageForm: 'Tablet', strength: '20 mg' },
    ],
  },
  {
    id: 5,
    orderNumber: 'ORD-005',
    customerName: 'Rustam Qodirov',
    status: "Jo'natildi",
    orderDate: '2024-08-09',
    pharmacyName: 'Apteka E',
    products: [
      { productName: 'Atorvastatin', quantity: 1, price: 12, dosageForm: 'Tablet', strength: '20 mg' },
      { productName: 'Simvastatin', quantity: 2, price: 14, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 6,
    orderNumber: 'ORD-006',
    customerName: 'Lola Abdullayeva',
    status: 'Yetkazib berildi',
    orderDate: '2024-08-11',
    pharmacyName: 'Apteka F',
    products: [
      { productName: 'Hydrochlorothiazide', quantity: 1, price: 3, dosageForm: 'Tablet', strength: '25 mg' },
      { productName: 'Amlodipine', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
  {
    id: 7,
    orderNumber: 'ORD-007',
    customerName: 'Shahzod Nabiyev',
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-13',
    pharmacyName: 'Apteka G',
    products: [
      { productName: 'Losartan', quantity: 2, price: 8, dosageForm: 'Tablet', strength: '50 mg' },
      { productName: 'Metoprolol', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '100 mg' },
      { productName: 'Furosemide', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '40 mg' },
    ],
  },
  {
    id: 8,
    orderNumber: 'ORD-008',
    customerName: 'Yulduzbek Ibragimov',
    status: "Jo'natildi",
    orderDate: '2024-08-15',
    pharmacyName: 'Apteka H',
    products: [
      { productName: 'Pantoprazole', quantity: 1, price: 9, dosageForm: 'Tablet', strength: '40 mg' },
      { productName: 'Lansoprazole', quantity: 1, price: 10, dosageForm: 'Capsule', strength: '30 mg' },
    ],
  },
  {
    id: 9,
    orderNumber: 'ORD-009',
    customerName: 'Nigina Ismoilova',
    status: 'Yetkazib berildi',
    orderDate: '2024-08-17',
    pharmacyName: 'Apteka I',
    products: [
      { productName: 'Levothyroxine', quantity: 2, price: 15, dosageForm: 'Tablet', strength: '100 mcg' },
      { productName: 'Warfarin', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
  {
    id: 10,
    orderNumber: 'ORD-010',
    customerName: "Ulug'bek Xayitov",
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-19',
    pharmacyName: 'Apteka J',
    products: [
      { productName: 'Digoxin', quantity: 1, price: 10, dosageForm: 'Tablet', strength: '250 mcg' },
      { productName: 'Clopidogrel', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '75 mg' },
    ],
  },
  {
    id: 11,
    orderNumber: 'ORD-011',
    customerName: 'Jamshid Ganiyev',
    status: 'Yetkazib berildi',
    orderDate: '2024-08-21',
    pharmacyName: 'Apteka K',
    products: [
      { productName: 'Glyburide', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '5 mg' },
      { productName: 'Glipizide', quantity: 2, price: 8, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 12,
    orderNumber: 'ORD-012',
    customerName: 'Mohira Matniyazova',
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-23',
    pharmacyName: 'Apteka L',
    products: [
      { productName: 'Prednisone', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '10 mg' },
      { productName: 'Prednisolone', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '20 mg' },
    ],
  },
  {
    id: 13,
    orderNumber: 'ORD-013',
    customerName: "Sarvar Jo'raev",
    status: "Jo'natildi",
    orderDate: '2024-08-25',
    pharmacyName: 'Apteka M',
    products: [
      { productName: 'Fluoxetine', quantity: 2, price: 10, dosageForm: 'Capsule', strength: '20 mg' },
      { productName: 'Sertraline', quantity: 1, price: 12, dosageForm: 'Tablet', strength: '50 mg' },
    ],
  },
  {
    id: 14,
    orderNumber: 'ORD-014',
    customerName: 'Dilshod Ismoilov',
    status: 'Yetkazib berildi',
    orderDate: '2024-08-27',
    pharmacyName: 'Apteka N',
    products: [
      { productName: 'Cetirizine', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '10 mg' },
      { productName: 'Loratadine', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '10 mg' },
      { productName: 'Montelukast', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 15,
    orderNumber: 'ORD-015',
    customerName: 'Otabek Yuldashev',
    status: "To'lovni kutmoqda",
    orderDate: '2024-08-29',
    pharmacyName: 'Apteka O',
    products: [
      { productName: 'Diphenhydramine', quantity: 1, price: 3, dosageForm: 'Tablet', strength: '25 mg' },
      { productName: 'Fexofenadine', quantity: 2, price: 7, dosageForm: 'Tablet', strength: '180 mg' },
    ],
  },
  {
    id: 16,
    orderNumber: 'ORD-016',
    customerName: 'Shahnoza Ergasheva',
    status: "Jo'natildi",
    orderDate: '2024-08-31',
    pharmacyName: 'Apteka P',
    products: [
      { productName: 'Ciprofloxacin', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '500 mg' },
      { productName: 'Metformin', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '500 mg' },
    ],
  },
  {
    id: 17,
    orderNumber: 'ORD-017',
    customerName: 'Dildora Ahmedova',
    status: "To'lovni kutmoqda",
    orderDate: '2024-09-01',
    pharmacyName: 'Apteka Q',
    products: [
      { productName: 'Lisinopril', quantity: 2, price: 10, dosageForm: 'Tablet', strength: '20 mg' },
      { productName: 'Amlodipine', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
  {
    id: 18,
    orderNumber: 'ORD-018',
    customerName: 'Jasurbek Iskandarov',
    status: 'Yetkazib berildi',
    orderDate: '2024-09-03',
    pharmacyName: 'Apteka R',
    products: [
      { productName: 'Atorvastatin', quantity: 1, price: 12, dosageForm: 'Tablet', strength: '20 mg' },
      { productName: 'Simvastatin', quantity: 2, price: 14, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 19,
    orderNumber: 'ORD-019',
    customerName: 'Nargiza Kurbanova',
    status: "Jo'natildi",
    orderDate: '2024-09-05',
    pharmacyName: 'Apteka S',
    products: [
      { productName: 'Omeprazole', quantity: 1, price: 8, dosageForm: 'Capsule', strength: '20 mg' },
      { productName: 'Pantoprazole', quantity: 1, price: 9, dosageForm: 'Tablet', strength: '40 mg' },
    ],
  },
  {
    id: 20,
    orderNumber: 'ORD-020',
    customerName: 'Farrukhbek Shukurov',
    status: 'Yetkazib berildi',
    orderDate: '2024-09-07',
    pharmacyName: 'Apteka T',
    products: [
      { productName: 'Levothyroxine', quantity: 2, price: 15, dosageForm: 'Tablet', strength: '100 mcg' },
      { productName: 'Warfarin', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
  {
    id: 21,
    orderNumber: 'ORD-021',
    customerName: 'Mamarasul Aliev',
    status: "To'lovni kutmoqda",
    orderDate: '2024-09-10',
    pharmacyName: 'Apteka U',
    products: [
      { productName: 'Hydrochlorothiazide', quantity: 1, price: 3, dosageForm: 'Tablet', strength: '25 mg' },
      { productName: 'Metoprolol', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '100 mg' },
    ],
  },
  {
    id: 22,
    orderNumber: 'ORD-022',
    customerName: 'Nodira Tashkentova',
    status: "Jo'natildi",
    orderDate: '2024-09-12',
    pharmacyName: 'Apteka V',
    products: [
      { productName: 'Furosemide', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '40 mg' },
      { productName: 'Losartan', quantity: 2, price: 8, dosageForm: 'Tablet', strength: '50 mg' },
    ],
  },
  {
    id: 23,
    orderNumber: 'ORD-023',
    customerName: 'Aslbek Sadykov',
    status: 'Yetkazib berildi',
    orderDate: '2024-09-15',
    pharmacyName: 'Apteka W',
    products: [
      { productName: 'Cetirizine', quantity: 1, price: 4, dosageForm: 'Tablet', strength: '10 mg' },
      { productName: 'Loratadine', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '10 mg' },
      { productName: 'Montelukast', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 24,
    orderNumber: 'ORD-024',
    customerName: 'Gulbahor Murodova',
    status: "To'lovni kutmoqda",
    orderDate: '2024-09-18',
    pharmacyName: 'Apteka X',
    products: [
      { productName: 'Diphenhydramine', quantity: 1, price: 3, dosageForm: 'Tablet', strength: '25 mg' },
      { productName: 'Fexofenadine', quantity: 2, price: 7, dosageForm: 'Tablet', strength: '180 mg' },
    ],
  },
  {
    id: 25,
    orderNumber: 'ORD-025',
    customerName: 'Azizbek Makhmudov',
    status: "Jo'natildi",
    orderDate: '2024-09-20',
    pharmacyName: 'Apteka Y',
    products: [
      { productName: 'Fluoxetine', quantity: 2, price: 10, dosageForm: 'Capsule', strength: '20 mg' },
      { productName: 'Sertraline', quantity: 1, price: 12, dosageForm: 'Tablet', strength: '50 mg' },
    ],
  },
  {
    id: 26,
    orderNumber: 'ORD-026',
    customerName: 'Shaxnoza Askarova',
    status: 'Yetkazib berildi',
    orderDate: '2024-09-22',
    pharmacyName: 'Apteka Z',
    products: [
      { productName: 'Glyburide', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '5 mg' },
      { productName: 'Glipizide', quantity: 2, price: 8, dosageForm: 'Tablet', strength: '10 mg' },
    ],
  },
  {
    id: 27,
    orderNumber: 'ORD-027',
    customerName: 'Shodibek Turaev',
    status: "To'lovni kutmoqda",
    orderDate: '2024-09-25',
    pharmacyName: 'Apteka AA',
    products: [
      { productName: 'Ciprofloxacin', quantity: 1, price: 7, dosageForm: 'Tablet', strength: '500 mg' },
      { productName: 'Metformin', quantity: 1, price: 6, dosageForm: 'Tablet', strength: '500 mg' },
    ],
  },
  {
    id: 28,
    orderNumber: 'ORD-028',
    customerName: 'Dilshodbek Mamatov',
    status: "Jo'natildi",
    orderDate: '2024-09-27',
    pharmacyName: 'Apteka AB',
    products: [
      { productName: 'Lisinopril', quantity: 2, price: 10, dosageForm: 'Tablet', strength: '20 mg' },
      { productName: 'Amlodipine', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
  {
    id: 29,
    orderNumber: 'ORD-029',
    customerName: 'Munira Murodova',
    status: "To'lovni kutmoqda",
    orderDate: '2024-09-29',
    pharmacyName: 'Apteka AC',
    products: [
      { productName: 'Omeprazole', quantity: 1, price: 8, dosageForm: 'Capsule', strength: '20 mg' },
      { productName: 'Pantoprazole', quantity: 1, price: 9, dosageForm: 'Tablet', strength: '40 mg' },
    ],
  },
  {
    id: 30,
    orderNumber: 'ORD-030',
    customerName: 'Aziza Raxmatullaeva',
    status: 'Yetkazib berildi',
    orderDate: '2024-10-01',
    pharmacyName: 'Apteka AD',
    products: [
      { productName: 'Levothyroxine', quantity: 2, price: 15, dosageForm: 'Tablet', strength: '100 mcg' },
      { productName: 'Warfarin', quantity: 1, price: 5, dosageForm: 'Tablet', strength: '5 mg' },
    ],
  },
]
